### PR TITLE
new tidy and glance methods for mira objects

### PR DESCRIPTION
**Pull request by vincentarelbundock**
This PR adds `glance` and a `tidy` methods for `mira` objects. It also includes documentation and a small set of tests.

``` r
remotes::install_github('vincentarelbundock/mice')

library(mice, warn.conflicts = FALSE)

imp <- mice(nhanes, maxit = 2, m = 2, seed = 1, printFlag = FALSE)
fit <- with(imp, lm(chl ~ age + bmi))

glance(fit)
#>   nimp nobs r.squared adj.r.squared
#> 1    2   25 0.5090581     0.4615265

tidy(fit)
#>          term   estimate  std.error  statistic    p.value           b       df
#> 1 (Intercept) -49.297489 101.371897 -0.4863033 0.67888855 4392.214948 1.822469
#> 2         age  38.277536  11.368686  3.3669270 0.01750532   28.544080 5.445895
#> 3         bmi   6.541489   3.079811  2.1239902 0.15909791    3.722905 2.142459
#>   dfcom       fmi    lambda m       riv        ubar
#> 1    22 0.7899569 0.6411206 2 1.7864510 3687.939041
#> 2    22 0.4896289 0.3312735 2 0.4953798   86.430903
#> 3    22 0.7486880 0.5887418 2 1.4315628    3.900882

tidy(fit, conf.int = TRUE)
#>          term   estimate  std.error  statistic    p.value    conf.low conf.high
#> 1 (Intercept) -49.297489 101.371897 -0.4863033 0.67888855 -528.822006 430.22703
#> 2         age  38.277536  11.368686  3.3669270 0.01750532    9.758638  66.79643
#> 3         bmi   6.541489   3.079811  2.1239902 0.15909791   -5.900299  18.98328
#>             b       df dfcom       fmi    lambda m       riv        ubar
#> 1 4392.214948 1.822469    22 0.7899569 0.6411206 2 1.7864510 3687.939041
#> 2   28.544080 5.445895    22 0.4896289 0.3312735 2 0.4953798   86.430903
#> 3    3.722905 2.142459    22 0.7486880 0.5887418 2 1.4315628    3.900882

tidy(fit, conf.int = TRUE, conf.level = .99)
#>          term   estimate  std.error  statistic    p.value     conf.low
#> 1 (Intercept) -49.297489 101.371897 -0.4863033 0.67888855 -1237.317387
#> 2         age  38.277536  11.368686  3.3669270 0.01750532    -5.690343
#> 3         bmi   6.541489   3.079811  2.1239902 0.15909791   -20.819404
#>    conf.high           b       df dfcom       fmi    lambda m       riv
#> 1 1138.72241 4392.214948 1.822469    22 0.7899569 0.6411206 2 1.7864510
#> 2   82.24541   28.544080 5.445895    22 0.4896289 0.3312735 2 0.4953798
#> 3   33.90238    3.722905 2.142459    22 0.7486880 0.5887418 2 1.4315628
#>          ubar
#> 1 3687.939041
#> 2   86.430903
#> 3    3.900882
```

<sup>Created on 2020-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by stefvanbuuren** [comment]
Thanks for your PR. A question:

`mice` defines the sequence of classes: `mids`, `mira` and `mipo`. The analysis results are stored in `mipo`, so to me that object seems a natural place to start. I was wondering why you take the `mira` object, and then add `out <- pool(x)` to create an object of class `mipo` at the function level?

**Comment by vincentarelbundock** [comment]
Sorry. For some reason I misread your post in the other thread and thought you wanted `tidy.mira`.

I can modify the PR to do `tidy.mipo` and `glance.mipo` instead.

That said, this will make us lose a few things, such as `pool.r.squared` for `lm` and `glm` objects. That was nice because the `glance` output typically includes such things when it can.

Just let me know what you would like and I'll make the change.

**Comment by stefvanbuuren** [comment]
Vincent, no problem. I guess I wasn't clear. 

I think it is best to do that all pooling by `mice::pool()`, so yes, please change `tidy.mira()` into `tidy.mipo()`.

For the `glance.mira()` I see your problem.  The `mipo` object holds no information on `r.squared` and the likes, so we would lose it from the model statistics. One option would be to extend the `mipo` class with model statistics, so that `mice::pool()` can then handle the pooling. Essentially, we could run `glance()` on each fitted model in the `mira` object, and append the results to the `tidy` tibble of model estimates (although I do not know whether we would run into complications if the model estimates are grouped). For some statistics (e.g. `r.squared`) we know how to pool it, for others (.e.g. `BIC`) I do not know how to do it.
 
A solution advocated in "R for Data Science" (p. 406) is to store glanced stats as list-column, and use `map()` to iterate over models. Perhaps we could move to something more like that when extending `mipo` to include model stats.

Incidentally, I found an error in the code (which - peculiarly - does not show up under Control-T):

```r
Error: Test failed: 'tidy.mira: nhanes lm'
* tmp$conf.low not equal to c(-171.676808396086, -12.5277617578218, 3.42203157045941).
3/3 mismatches (average diff: 130)
[1] -528.82 - -171.68 == -357.15
[2]    9.76 -  -12.53 ==   22.29
[3]   -5.90 -    3.42 ==   -9.32
* tmp$conf.low not equal to c(-216.910255354075, -63.8124944550467, 2.16193377446054).
3/3 mismatches (average diff: 367)
[1] -1237.32 - -216.91 == -1020.4
[2]    -5.69 -  -63.81 ==    58.1
[3]   -20.82 -    2.16 ==   -23.0
```

**Comment by vincentarelbundock** [comment]
Personally, I'm not a big fan of data.frames in data.frames or lists in lists. I find them very unintuitive and hard to introspect. I would suggest modifying the `mipo` object produced by `pool` using something like this:

```r
glancedf <- summary(getfit(object), type = 'glance', dfcom = dfcom)
pooled <- pool.fitlist(getfit(object), dfcom = dfcom)
rr <- list(call = call, m = m, pooled = pooled, glancedf = glancedf)
```

`glancedf` is just a dataframe of model features with one row per model. This would make it easy to add support for `mipo` objects in functions like `pool.r.squared`.

The testing error is super weird. But it doesn't seem to be related my changes. I created a new branch in my fork called `tidymipo`: https://github.com/vincentarelbundock/mice/tree/tidymipo

The only difference between this branch and master is that I added a test for `pool.r.squared`. This test passes when I run it interactively by cut-paste, but it fails when I run it with `devtools::test()`.

I tried a few things, but can't quite figure out why this is.

**Comment by stefvanbuuren** [comment]
Yes, that's an elegant solution for extending the `mipo` object. The `glancedf` table of model statistics is informative in itself, and feeds into a `glance.mipo()` function.

Would you be willing to implement this in your PR?

**Comment by vincentarelbundock** [comment]
Sounds good. I'll start a new PR with more incremental commits so we can diagnose the weird testing errors at different stages.

**Comment by vincentarelbundock** [comment]
Also maybe call the object `glanced` to match verb tense with `pooled`

**Comment by stefvanbuuren** [comment]
Yes, fine of course.

I don't think the weird testing error is related to `mice`, BTW.

**Pull request closed without merging**
