### PR TITLE
Fix calculations in D3() for calculating likelihood ratio tests

### PR DESCRIPTION
**Pull request by biswas2**
Simply, first, calculate the value of the log-likelihood functions for the full model and for the restricted model. Then, determine the average of the likelihood ratio tests. Please note that the existing D3() function gives incorrect results.

### CODE REVIEW

**Comment by stefvanbuuren** [comment]
Dear Rasel, thanks for your contribution. 

It seems that there is an error in `D3()`, which indeed needs to be fixed. The problem and your solution is related to #226. I will study your fix, and get back to you. 

Best, Stef.

**Comment by stefvanbuuren** [comment]
We need some additional testing to see whether `D3` is now correct.

Commit https://github.com/stefvanbuuren/mice/commit/15f3dd141d9d99ff60a9523c51777ea37d648141 adds lines from #226 to `tests/testthat/test-D3.R`. For complete `lrlmtest::lrtest`, `mitml::testModels` and `mice::D3` now produce the same value for the test statistic, which is good progress.

I am still uncertain about the discrepancies between `mitml::testModels` and `mice::D3` for multiply imputated data.  File `tests/testthat/test-D3.R` contains four (outcommented) tests that fail. It would be reassuring to know where the differences stem from, and which version should be preferred.

**Comment by biswas2** [comment]
In `mice::D3`, from the _m_ repetitions of the full (or null) models, it calculates the mean of the estimates of the (fixed) parameter coefficients, _B-HAT_, and then for each imputed dataset, it calculates the likelihood for the model with the parameters constrained to _B-HAT_.

In `mitml::testModels`, from the _m_ repetitions of the full (or null) models, it calculates the mean of the estimates of both the (fixed) coefficients, _B-HAT_, and the variance component, _SIGMA^2_, and then for each imputed dataset, it calculates the likelihood for the model with the parameters constrained to (_B-HAT_, _SIGMA^2_).

Though the results are not very different for non-mixed models, I wonder which one is more appropriate.

**Comment by stefvanbuuren** [comment]
Rasel, 

I contacted Simon Grund, the author of [`mitml`](https://github.com/simongrund1/mitml), on his thoughts about calculating the LR test, especially for multilevel data. 

He prefers to be able to fix the variance components in multilevel models. The `mitml` package contains dedicated methods for doing this for selected multilevel models. 

The `mice::D3()` function relies on the standard update for statistical models in R, and thus should work for a wider range of models. A [post of Ben Bolker](https://stackoverflow.com/questions/39718754/fixing-variance-values-in-lme4) shows how to fix variances in `lmer`, but it's too complex and too specific to incorporate this into the generic `mice::fix.coef()` workhorse. 

I therefore leave `mice::fix.coef()` as it currently is. The documentation of `D3()` explains why the LR results differ between `mitml` and `mice`. In the future, it may become easier to constrain variance component, so perhaps then we might use it. Users interested in the technical details, consults [Bolker's FAQ](http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#tests-of-effects-i.e.testing-that-several-parameters-are-simultaneously-zero).

Thanks for your contribution.

**Pull request merged**
