### PR TITLE
various minor changes for efficiency and robustness

### PR DESCRIPTION
**Pull request by bfgray3**
This pull request does not change any functionality, but aims to improve the efficiency and robustness of the package.  It seeks to accomplish the following:

* Tests
    + prefer more specific tests than `expect_true` when possible
* R scripts
    + use logical vectors as-is in logical tests, without using `==`
    + prefer `file.path` over `paste` when constructing file names
    + favor `vapply` over `sapply`
    + use double logical operators in `if` statements where a length-one result is desired
    + prefer `paste0` over `paste(..., sep = "")`
    + avoid `which` when the original logical vector will suffice
    + preallocate vectors before loops in order to avoid growing them inside loops
    + favor `*.int` internal functions over more abstracted versions, e.g. `rep.int` over `rep`
    + use `*apply` functions when possible instead of a `for` loop
    + prefer `seq_len` and `seq_along` over `1:*`
    + only use `ifelse` when a vectorized comparison is desired; use `if` and `else` otherwise

### CODE REVIEW

**Comment by stefvanbuuren** [comment]
Thanks a lot. This is great, and the code looks certainly much better with these changes. 

I cannot, however, readily merge your changes into the `master` branch because some changes break the example code. For example, `sample.int()` in `ampute.Rmd` does not work, or the `with()` function is broken because of the introduction of the `f()` function. 

Would you mind testing your changes against the code in the examples and the `R` code in `inst/doc`? If that works, then I'd be happy to consider merge.

**Comment by bfgray3** [comment]
Thanks for your patience.  I have made some updates and now I get the following output from `devtools::check(".")`:

```
R CMD check results
0 errors | 0 warnings | 1 note 
checking compiled code ... NOTE
File 'mice/libs/x64/mice.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

It is good practice to register native routines and to disable symbol
search.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
 WARNING
'qpdf' is needed for checks on size reduction of PDFs
```

**Comment by bfgray3** [comment]
@stefvanbuuren kindly let me know if my fix to the above problems is satisfactory.

**Comment by stefvanbuuren** [comment]
Looks good now. Will merge. Thanks for your kind contribution.
If you want to be included as contributor, please send me your email address.

**Comment by bfgray3** [comment]
@stefvanbuuren no problem--glad I could help.  Thank you for your kindness and understanding in the pull request process.  I'd love to be included as a contributor; my email address is bfgray3@gmail.com.--Bernie Gray

**Pull request merged**
